version: '3.8' 
services: 
  backend:  
    build: .
    container_name: backend
    networks:
      - main
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend # Mount the current directory as a volume
 # Expose port 8000
    # expose:
    #   - 8000
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # network_mode: host
    restart: always
